kind: Service
apiVersion: v1
metadata:
  name: front-service
spec:
  selector:
    app: testapp-service
  ports:
    - name: front-service-port
      targetPort: 8080
      port: 8080
      protocol: TCP
